myportal/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView    
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portal.urls', namespace='portal')),
    
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api-login/', include('rest_framework.urls')),
]

portal/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    register_employee , search_collaborator,
    view_all_collaborators, confirm_identity,
    collaborators_api, collaborator_api,
    binary_search, sort_array, login,
    things_to_by, things_to_by_filter,
    all_things_to_buy_by_category,
    all_things_to_buy_by_priority,
    get_categories, get_all_items,
    delete_item, get_item_by_pk,
    update_item, login, all_items_order_by,
    selenium_practie, calculate,
    distance_between_two_places,
    distance_between_two_places_api,
    color_picker, color_picker_api,
    color_search, total_colors,
    file_information,

    fraction_calculator,
    calculate_fractions,
)
from .api_views import (
    CollaboratorViewSet,
    ItemToBuyViewSet,
    CollaboratorView,
    ItemToBuyView,
    CalculatorView,
    CalculatorViewSet,
    MovieViewSet,
    ResourceViewSet,
    UserProfileViewSet,
    UserReadWriteViewSet,
    AccountViewSet,
    CommentViewSet,
)


app_name = 'portal'

router = DefaultRouter()
router.register('collaborators', CollaboratorViewSet)
router.register('items', ItemToBuyViewSet)
router.register('calculations', CalculatorViewSet)
router.register('movie', MovieViewSet)
router.register('resource', ResourceViewSet)
router.register('user', UserProfileViewSet)
router.register('user-2', UserReadWriteViewSet)
router.register('account', AccountViewSet)
router.register('comment', CommentViewSet)


urlpatterns = [
    path('calculate_fractions/<str:nume1>/<str:deno1>/<str:nume2>/<str:deno2>/<str:operator>/',
         calculate_fractions),
    path('fraction_calculator/', fraction_calculator,
         name='fraction_calculator'),
    path('file_information/', file_information,
         name='file_information'),
    path('total_colors/', total_colors),
    path('color_search/<int:limit>/', color_search),
    path('color_picker/', color_picker),
    path('color_picker_api/', color_picker_api),
    path('distance_between_two_places/',
         distance_between_two_places,
         name='distance_between_two_places'),
    path('distance_between_two_places_api/',
         distance_between_two_places_api),
    path('selenium_practice/', selenium_practie,
         name='selenium_practice'),
    path('calculate/<str:first_number>/<str:second_number>/<str:operator>/',
         calculate),
    path('login/', login, name='login'),
    path('register/', register_employee, name='register'),
    path('things_to_buy/', things_to_by, name='things_to_by'),
    path('all_items_order_by/<str:colname>/', all_items_order_by),
    
    path('search/<str:username>/', search_collaborator,
         name='search'),
    path('collaborators/', view_all_collaborators,
         name='all_collaborators'),
    path('confirm_identity/<str:username>/', confirm_identity,
         name='confirm_identity'),
    path('binary_search/', binary_search, name='binary_search'),
    path('sort_array/<str:arr>/', sort_array),
    
    path('things_to_by/<str:category>/', things_to_by_filter, name='things_to_by_filter'),
    path('all_things_to_buy_by_category/<str:category>/', all_things_to_buy_by_category),
    path('all_things_to_buy_by_priority/<str:priority>/', all_things_to_buy_by_priority),
    path('get_categories/', get_categories),
    path('get_all_items/', get_all_items),
    path('delete_item/<int:pk>/', delete_item, name='delete_item'),
    path('get_item_by_pk/<int:pk>/', get_item_by_pk),
    path('update_item/', update_item),
    # path('login/', login, name='login'),
    
    # APIs
    # path('api/collaborators/', collaborators_api),
    # path('api/collaborators/<str:first_name>/', collaborator_api),
    
    path('api/', include(router.urls)),
    path('xml/collaborators/', CollaboratorView.as_view()),
    path('xml/items/', ItemToBuyView.as_view()), 
    path('xml/calculations/', CalculatorView.as_view()),
]

portal/models.py
from django.db import models
from django.utils import timezone
from django.db.models import Aggregate, Sum
from django.contrib.auth.models import User

import json
import random
import string
from dataclasses import dataclass
from math import asin, cos, radians, sin, sqrt


def all_digits(num):
    for x in num:
        try:
            x = int(x)
        except:
            return False
    return True


class Color(models.Model):
    red = models.IntegerField()
    green = models.IntegerField()
    blue = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('id',)
    
    def __str__(self):
        return "({0}, {1}, {2}) - #{0:02x}{1:02x}{2:02x}".format(
            self.red, self.green, self.blue,
            self.red, self.green, self.blue
        )
    
    def hexcolor(self):
        return "#{0:02x}{1:02x}{2:02x}".format(
            self.red, self.green, self.blue    
        )
    
    def rgbcolor(self):
        return "({0}, {1}, {2})".format(
            self.red, self.green, self.blue    
        )

@dataclass
class Position:
    name: str
    lon: float = 0.0
    lat: float = 0.0

    def distance_to(self, other):
        r = 6371  # Earth radius in kilometers
        lam_1, lam_2 = radians(self.lon), radians(other.lon)
        phi_1, phi_2 = radians(self.lat), radians(other.lat)
        h = (sin((phi_2 - phi_1) / 2)**2
             + cos(phi_1) * cos(phi_2) * sin((lam_2 - lam_1) / 2)**2)
        return 2 * r * asin(sqrt(h))


class Distance(models.Model):
    latitude1 = models.FloatField()
    longetude1 = models.FloatField()
    latitude2 = models.FloatField()
    longetude2 = models.FloatField()
    
    def __str__(self):
        return f'({self.latitude1}ºN, {self.longetude1}ºE) ({self.latitude2}ºN {self.longetude2}ºE)'
    
    def distance_to(self):
        city_1 = Position('Maputo', self.latitude1, self.longetude1)
        city_2 = Position('New York', self.latitude2, self.longetude2)
        distance = city_1.distance_to(city_2)
        distance = round(distance, 4)
        return distance


class Comment(models.Model):
    author = models.ForeignKey(to=User, on_delete=models.CASCADE)
    datetime = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    
    def __str__(self):
        return self.author.username
    
    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        

class Account(models.Model):
    username = models.CharField(max_length=32)
    
    def __str__(self):
        return self.username
    
    class Meta:
        verbose_name = 'Account'
        verbose_name_plural = 'Accounts'
    


class UserProfile(models.Model):
    user = models.OneToOneField(to=User, 
                                on_delete=models.CASCADE)
    bio = models.TextField()
    birth_date = models.DateField()

    def __str__(self):
        return f'{self.user.username} profile'


class Resource(models.Model):
    title = models.CharField(max_length=256)
    content = models.TextField()
    liked_by = models.ManyToManyField(to=User)

    def __str__(self):
        return f'{self.title}'
    
    class Meta:
        verbose_name = 'Resource'
        verbose_name_plural = 'Resources'


class Movie(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048)
    release_date = models.DateField()
    rating = models.PositiveSmallIntegerField()

    us_gross = models.IntegerField(default=0)
    worldwide_gross = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.title}'
    
    class Meta:
        verbose_name = 'Movie'
        verbose_name_plural = 'Movies'



OPERATIONS = {
    "sum": lambda x, y: x + y,
    "sub": lambda x, y: x - y,
    "div": lambda x, y: x / y,
    "multi": lambda x, y: x * y
}

GET_OPERATOR = {
    "sum": "+", "sub": "-", "div": ":", "multi": "*"
}

class Calculator(models.Model):
    first_number = models.FloatField()
    second_number = models.FloatField()
    operator = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.first_number} {GET_OPERATOR[self.operator]} {self.second_number} = {self.result()}'
    
    def result(self):
        res = OPERATIONS[self.operator](self.first_number, self.second_number)
        return round(res, 2)
        
    class Meta:
        verbose_name = 'Calculation'
        verbose_name_plural = 'Calculations'
        
    def serialize(self):
        data = {
            'id': self.id,
            'item_name': self.first_number,
            'price': self.second_number,
            'quantity': self.operator,
            'result': self.result(),
            'created_at': self.created_at,
            'updated_at': self.updated_at,
        }
        return data
    

def format_username(username):
    letters = string.ascii_letters
    if (len(username) == 7 and username[0] in list('abc') and 
        all_digits(username[1:])):
        return username
    raise TypeError('Username must start with a letter and remaining characters must be digits')


def generate_digits():
    letter = random.choice(list('abc'))
    digits = ''.join([str(random.randint(1, 9)) for _ in range(6)])
    return letter + digits


class ItemToBuyQuerySet(models.QuerySet):
    def serialize(self):
        return json.dumps(self.model('id', 'item_name', 'price', 'quatity',
                                     'priority', 'category', 'urgent', 
                                     'created_at', 'updated_at'))
    
class ItemToBuyManager(models.Manager):
    def get_queryset(self):
        return ItemToBuyQuerySet(self.model, 
                                 using=self._db)
    # PersonQuerySet(self.model, using=self._db)

class ItemToBuy(models.Model):
    CATEGORY = (
        ('clothes', 'Clothes'),
        ('cotas', 'Cotas'),
        ('debt', 'Debt'),
        ('documents', 'Documents'),
        ('family', 'Family'),
        ('food', 'Food'),
        ('house', 'House'),
        ('hygien', 'Hygien'),
        ('utilities', 'Utilities')
    )
    PRIORITY = (
        ('critical', 'Critical'),
        ('moderate', 'Moderate'),
        ('low', 'Low')
    )
    BUY_FROM = (
        ('side-hustle', 'Side-Hustle'),
        ('salary', 'Salary')
    )
    item_name = models.CharField(max_length=255, unique=True)
    price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.0)
    quantity = models.IntegerField()
    category = models.CharField(max_length=20, 
                                choices=CATEGORY,
                                default='hygien')
    priority = models.CharField(max_length=20, 
                                choices=PRIORITY,
                                default='critical')
    urgent = models.BooleanField(default=True)
    buy_from = models.CharField(max_length=20,
                                choices=BUY_FROM,
                                default='cabaz')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    objects = ItemToBuyManager()
    
    def __str__(self):
        return f'{self.item_name} - {self.price} MZN - {self.quantity} items'
    
    class Meta:
        ordering = ('item_name',)
        verbose_name = ('Item To Buy')
        verbose_name_plural = ('Items To Buy')
        
    def serialize(self):
        data = {
            'id': self.id,
            'item_name': self.item_name,
            'price': self.price,
            'quantity': self.quantity,
            'category': self.category,
            'priority': self.priority,
            'urgent': self.urgent,
            'total_amount': self.total_amount(),
            'credit': self.credit(),
            'created_at': self.created_at,
            'updated_at': self.updated_at
        }
        return data
    
    def total_amount(self):
        total = 0
        for item in ItemToBuy.objects.all():
            total += item.price
        return total
    
    def credit(self):
        return 38400 - self.total_amount()


class ColaboratorQuerySet(models.QuerySet):
    def serialize(self):
        return json.dumps(self.model('id', 'username',
                                     'first_name'))
    
class ColaboratorManager(models.Manager):
    def queryset(self):
        return ColaboratorQuerySet(self, self._db)


class Colaborator(models.Model):        
    DEPTS = (
        ('engineering', 'Engineering'),
        ('cib', 'CIB'),
        ('bcc', 'BCC'),
        ('chnw', 'CHNW')
    )
    username = models.CharField(max_length=50, 
                                unique=True, 
                                blank=True,
                                default=generate_digits)
    first_name = models.CharField(max_length=125)
    last_name = models.CharField(max_length=125)
    email = models.EmailField(blank=True, unique=True)
    department = models.CharField(max_length=20,
                                  choices=DEPTS,
                                  default='engineering')
    # department = models.CharField(max_length=200,
    #                               blank=True,
    #                               null=True)
    division = models.CharField(max_length=200,
                                blank=True,
                                null=True)
    job_title = models.CharField(max_length=200,
                                 blank=True,
                                 null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    
    objects = ColaboratorManager()
    
    def __str__(self):
        return f'{self.last_name.upper()} {self.first_name}'
    

portal/forms.py
from django import forms
from django.contrib.auth.models import User

from random import randint

from .models import Colaborator, ItemToBuy


class FileInformation(forms.Form):
    file = forms.FileField()
    

class ItemToBuyForm(forms.ModelForm):
    class Meta:
        model = ItemToBuy
        fields = '__all__'


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')


class LoginForm(forms.Form):
    # class Meta:
    #     model = User
    #     fields = ['username', 'password']
    
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        # 'value': 'januario95'    
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        # 'value': 'Jaci1995'    
    }))
    


class BinarySearchForm(forms.Form):
    number1 = forms.IntegerField()
    number2 = forms.IntegerField()
    number3 = forms.IntegerField()
    number4 = forms.IntegerField()
    number5 = forms.IntegerField()
    number6 = forms.IntegerField()
    number7 = forms.IntegerField()
    number8 = forms.IntegerField()
    number9= forms.IntegerField()
    

class CollaboratorForm(forms.ModelForm):
    # email = forms.EmailField(widget=forms.EmailInput(attrs={
    #     'placeholder': 'first.last@portal.co.mz',
    #     'value': 'first.last@portal.co.mz'
    # }))
    
    class Meta:
        model = Colaborator
        fields = ['first_name', 'last_name',
                  'department', 'division', 'job_title']
        
        
        

portal/templates/portal/all_collaborators.html
<html DOCTYPE>
<html>
<head>
    <meta charset="utf-8">
    <style>
        .container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .collaborator table {
            width: 100%;
            border-collapse: collapse;
        }
        .collaborator table th,
        .collaborator table td {
            border: 1px solid #ddd;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header-div">
            <h4>Colaborators</h4>
        </div>
        <div class="body-div">
            <div class="collaborator">
                <select id="filter">
                    {% for option in fields %}
                        <option value="{{ option }}">{{ option }}</option>
                    {% endfor %}
                </select>
                <br/>
                <br/>
                <table>
                    <thead>
                        <tr>
                            <th>Username</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Department</th>
                            <th>Division</th>
                            <th>Job Title</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for collaborator in collaborators %}
                            <tr>
                                <td>{{ collaborator.username }}</td>
                                <td>{{ collaborator.first_name }}</td>
                                <td>{{ collaborator.last_name }}</td>
                                <td>{{ collaborator.email }}</td>
                                <td>{{ collaborator.department }}</td>
                                <td>{{ collaborator.division }}</td>
                                <td>{{ collaborator.job_title }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="{% url 'portal:register' %}">Register New</a>
            </div>
        </div>
    </div>
    
    <script>
        /*
        let check_identity = prompt('Enter your username?', '');
        fetch(`/confirm_identity/${check_identity}/`, {
            method: 'GET'
        })
            .then(res => res.json())
            .then(data => {
                let username_exists = data.username_exists;
                if (username_exists) {
                    //
                } else {
                    window.location = '/register/';
                }
            })
            .catch(err => console.log(err));
        */
    </script>
</body>
</html>

portal/templates/portal/binary_search.html
{% load static %}
<html DOCTYPE>
<html>
<head>
    <meta charset="utf-8">
    <style>
        .container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <div class="container">
        
    </div>
    
    <script src="{% static 'jquery-3.6.1.js' %}"></script>
    <script>
        
    </script>
</body>
</html>

portal/templates/portal/color_picker.html
{% load static %}
<html DOCTYPE>
<html>
<head>
    <meta charset="utf-8">
    <title>Color Picker</title>
    <style>
        .container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            margin-top: 10px;
        }
        .color-setter {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .color-input {
            width: 150px;
            height: 50px;
        }
        input {
            text-align: center;
        }
        .btn {
            margin-top: 10px;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h4>Color Picker</h4>
        <div class="color-picker">
            <input type="color" class="color-input">
            <span class="hexcolor-code">#d4814b</span>
        <div>
        <div class="color-setter">
            <label>Red</label>
            <input type="number" class="red" value=34>
            <label>Green</label>
            <input type="number" class="green" value=204>
            <label>Blue</label>
            <input type="number" class="blue" value=96>
            <input type="submit" class="btn" value="Convert">
            <input type="submit" class="generate-color" value="Generate values">
        </div>
    </div>
    
    <script src="{% static 'jquery-3.6.1.js' %}"></script>
    <script>
        let color_input = document.querySelector('.color-input');
        console.log(color_input.value);
        color_input.value = "#d4814b";
        console.log(color_input.value);

        let color_picker = document.querySelector(".color-input");
        let hexcolor_code = document.querySelector(".hexcolor-code");
        let red = document.querySelector(".red");
        let green = document.querySelector(".green");
        let blue = document.querySelector(".blue");
        let convert = document.querySelector(".btn");
        let generate_color = document.querySelector(".generate-color");
        
        color_picker.value = "#37d6e1";
        
        generate_color.addEventListener("click", e => {
            generateColor();
        });
        
        function generateNumber() {
            let num = Math.round(Math.random() * 255);
            return num;
        }
        
        generateColor();
        function generateColor() {
            red.value = generateNumber();
            green.value = generateNumber();
            blue.value = generateNumber();
        }
        
        convert.addEventListener("click", e => {
            e.preventDefault();
            let csrf_token = "{{ csrf_token }}";
            
            let data = {
                "red": red.value,
                "green": green.value,
                "blue": blue.value
            }
            
            fetch("/color_picker_api/", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "X-CSRFToken": csrf_token
                },
                body: JSON.stringify(data)
            })
                .then(res => res.json())
                .then(data => {
                    let color = data.color;
                    color_picker.value = color;
                    hexcolor_code.textContent = color;
                })
                .catch(err => console.log(err));
        })
        
        color_picker.addEventListener("change", e => {
            hexcolor_code.textContent = e.target.value;
        });
    </script>
</body>
</html>

portal/templates/portal/file_information.html
{% load static %}
<html DOCTYPE>
<html>
<head>
    <meta charset="utf-8">
    <title>File Information</title>
    <style>
        .container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {{ form }}
            {% csrf_token %}
            <input type="submit" value="Check Info">
        </form>
        
        <div class="file-info">
        
        </div>
    </div>
    
    <script src="{% static 'jquery-3.6.1.js' %}"></script>
    <script>
        
    </script>
</body>
</html>

portal/templates/portal/register_employee.html
<html DOCTYPE>
<html>
<head>
    <meta charset="utf-8">
    <style>
        .container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .collaborator table {
            width: 100%;
            border-collapse: collapse;
        }
        .collaborator table th,
        .collaborator table td {
            border: 1px solid #ddd;
        }
        .confirm-identity {
            display: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header-div">
            <h4>Colaborator {{ title }}</h4>
        </div>
        <div class="body-div">
            {% if only_form %}
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Register">
                    <a class="view-collaborators" href="#">View Collaborators</a>
                </form>
                <div>
                    <span class="error"></span>
                </div>
                <div class="confirm-identity">
                    <input class="username" type="text" placeholder="Enter your username" required>
                    <button class="confirm-user">Validate</button>
                </div>
            {% endif %}
            {% if user_exists %}
                <h4 style="color:red">Collaborators with these details already exists!</h4>
            {% endif %}
            <div class="collaborator">
                {% if is_created %}
                    <table>
                        <thead>
                            <tr>
                                <th>Username</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email</th>
                                <th>Department</th>
                                <th>Division</th>
                                <th>Job Title</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ collaborator.username }}</td>
                                <td>{{ collaborator.first_name }}</td>
                                <td>{{ collaborator.last_name }}</td>
                                <td>{{ collaborator.email }}</td>
                                <td>{{ collaborator.department }}</td>
                                <td>{{ collaborator.division }}</td>
                                <td>{{ collaborator.job_title }}</td>
                            </tr>
                        </tbody>
                    </table>
                    <a href="{% url 'portal:register' %}">Register New</a>
                {% endif %}
            </div>
        </div>
    </div>
    
    <script>
        let firstName = document.querySelector('#id_first_name');
        let lastName = document.querySelector('#id_last_name');
        let division = document.querySelector('#id_division');
        let jobTitle = document.querySelector('#id_job_title');
        let viewCollaborators = document.querySelector('.view-collaborators');
        let confirm_identity = document.querySelector('.confirm-identity');
        let username = document.querySelector('.username');
        let confirm_btn = document.querySelector('.confirm-user');
        let error = document.querySelector('.error');
        
        firstName.focus();
        
        viewCollaborators.addEventListener("click", e => {
            let check_identity = prompt('Enter your username?', '');
            fetch(`/confirm_identity/${check_identity}/`, {
                method: 'GET'
            })
                .then(res => res.json())
                .then(data => {
                    let username_exists = data.username_exists;
                    if (username_exists) {
                        window.location = '/collaborators/';
                    } else {
                        window.location = '/register/';
                    }
                })
                .catch(err => console.log(err));
        });
        
        confirm_btn.addEventListener("click", e => {
            if (username.value === "") {
                error.textContent = "Enter your username!"
                error.style.color = "red";
                error.style.fontSize = "14px";
                error.style.fontStyle = "italic";
            } else {
                fetch(`/confirm_identity/${username.value}/`, {
                    method: 'GET',
                })
                    .then(res => res.json())
                    .then(data => {
                        let username_exists = data.username_exists;
                        if (username_exists) {
                             error.textContent = "";
                             window.location = "/collaborators/"
                        } else {
                            error.textContent = "You don't have permission to view this!";
                            error.style.color = "red";
                            error.style.fontSize = "14px";
                            error.style.fontStyle = "italic";
                        }
                    })
                    .catch(err => console.log(err));
            }
        });
    </script>
</body>
</html>

portal/templates/portal/search-collaborator.html
<html DOCTYPE>
<html>
<head>
    <meta charset="utf-8">
    <style>
        .container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .collaborator table {
            width: 100%;
            border-collapse: collapse;
        }
        .collaborator table th,
        .collaborator table td {
            border: 1px solid #ddd;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header-div">
            <h4>Colaborator Details</h4>
        </div>
        <div class="body-div">
            <div class="collaborator">
                <table>
                    <thead>
                        <tr>
                            <th>Username</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>Department</th>
                            <th>Division</th>
                            <th>Job Title</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ collaborator.username }}</td>
                            <td>{{ collaborator.first_name }}</td>
                            <td>{{ collaborator.last_name }}</td>
                            <td>{{ collaborator.email }}</td>
                            <td>{{ collaborator.department }}</td>
                            <td>{{ collaborator.division }}</td>
                            <td>{{ collaborator.job_title }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
    <script>
        let first_name = document.querySelector('#id_first_name');
        let last_name = document.querySelector('#id_last_name');
        let department = document.querySelector('#id_department');
        let division = document.querySelector('#id_division');
        let job_title = document.querySelector('#id_job_title');
        
        first_name.value = 'Januario';
        last_name.value = 'Cipriano';
        department.value = 'Engineering';
        division.value = 'Data and Analytics';
        job_title.value = 'Robotics Automation Engineer';
        
        first_name.addEventListener('input', e => {
            let val = e.target.value;
        });
    </script>
</body>
</html>